# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests and Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  code_validator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: ✔ HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
          root: florist-blaklint/
          css: true

  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f tests/test_requirements.txt ]; then pip install -r tests/test_requirements.txt; fi
    - name: start live server # Start a live-server for testing the webpage content
      run: |
        cd florist-blaklint/
        python -m http.server & 
    - name: Run Tests scripts on localhost
      run: python tests/seleniumTests.py http://localhost:8000/

  screenshot:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16


      - name: installing chromium
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update 
          sudo apt-get install -y google-chrome-stable

      - name: Starting live server
        run: npx serve florist-blaklint/ &

      - name: Installing dependencies
        run: npm ci
      
      - name: Run screenshot script
        run: npm run takescreenshots --no-sandbox

      - name: Upload screenshots as artifact
        uses: actions/upload-artifact@v2 # Uplaod screenshots to Actions Artifacts via actions/upload-artifact@v2
        with:
          path: screenshots/
          name: Page screenshots
  deploy:
    permissions:
      contents: write
    needs: [ code_validator, run_tests ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Deploy website 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: florist-blaklint # The folder that should be used in the deployment